Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/Users/usi/Desktop/Project_7_Kaan_Sen/hpc-python/pde-miniapp-py/main.py", line 1, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[48466,1],8]
  Exit code:    1
--------------------------------------------------------------------------
